image: docker:19.03.12
services:
  - docker:19.03.12-dind
stages:
  - build
  - review
  - deploy

variables:
  LATEST_VERSION: latest
  MAJOR_VERSION: 1.6.1
  PACKER_VERSION: 1.6.1
  DOCKER_IMAGE: packer-with-win-update
  WIN_UPDATE_PROVISIONER_VERSION: 0.10.0
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  CI_REGISTRY_USER: tvories
  CI_REGISTRY_PASSWORD: blargington
  CI_REGISTRY_IMAGE: ${CI_REGISTRY_USER}/${DOCKER_IMAGE}


before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":"$LATEST_VERSION" -t "$CI_REGISTRY_IMAGE":"$MAJOR_VERSION" --build-arg PACKER_VERSION=$PACKER_VERSION --build-arg WIN_UPDATE_PROVISIONER_VERSION=$WIN_UPDATE_PROVISIONER_VERSION .
    - docker push "$CI_REGISTRY_IMAGE":"$LATEST_VERSION" 
    - docker push "$CI_REGISTRY_IMAGE":"$MAJOR_VERSION"